### ISSUE TITLE
Can u do a YouTube video explaining how to install the bot??

### ISSUE THREAD

**Issue by Polin2711** [whuybrec/MiniGamesBot#6]
Thanks

**Comment by whuybrec** [comment]
Hey!
I am not working on the bot anymore, so not gonna spent time making a YT video explaining how to install it. There's an elaborate readme which will help you do that. If you are stuck somewhere, I'm happy to help you fix it. As I said before, I'm not working on the bot anymore, so it could be that there are some libraries which are not supported anymore (I've heard the Discord api changed a bit).
